"""empty message

Revision ID: 265c2067656f
Revises: a9e0be0d3321
Create Date: 2020-02-19 08:52:15.084029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265c2067656f'
down_revision = 'a9e0be0d3321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    # ### end Alembic commands ###
